<a href="https://colab.research.google.com/github/gayathri9381/TNS.ipynb/blob/main/Neural_N_w_Architecture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Agenda
1. Forward Propagation
2.  Loss Functions
3. Backward Propagation
4. Gradient Descent
----------------------------------------


#1. Forward Propagation
Definition

Forward Propagation is the process of passing the input data through the neural network to generate the final prediction (output).

It is called forward because the information moves only in one direction:

Input Layer → Hidden Layer(s) → Output Layer

No learning happens here.

The model simply makes a prediction using the current weights and biases.

Simple Real-Life Example

Imagine a student writing an exam.

Input:

Study Hours

Sleep Hours

Attendance

↓

Brain Processes Information

↓

Prediction:

Pass /
Fail

The student's brain processes the information before giving the final decision.

Similarly,

Neural Network

Input → Hidden Layers → Prediction


##Flow of Forward Propagation
Input->
Weighted Sum (Z)->
Activation Function->
Output Prediction

-------------------------------------


#2. Loss Functions
##Why Do We Need a Loss Function?

After Forward Propagation, the neural network gives a prediction.

Now we compare:

Prediction with Actual Value

If both are different,

there is an error.

A Loss Function measures how wrong the prediction is.

Without a loss function, the model would have no way to know whether it is making good or bad predictions.

--------------------------------


##Error Vs Loss


| Error                         | Loss                                |
| ----------------------------- | ----------------------------------- |
| Difference for one data point | Average error over many data points |
| Individual prediction         | Entire dataset                      |
| Local                         | Overall Performance                 |

-------------------------------------------
Types of Loss Functions

There are mainly three types used frequently.

a. Mean Squared Error (Regression)

b. Binary Cross Entropy (Binary Classification)

c. Categorical Cross Entropy (Multi-Class Classification)


#a. Mean Squared Error (MSE)

Used For->Regression

Examples

House Price Prediction,
Salary Prediction,
Temperature Prediction.

Formula: MSE=1/n(​∑(y−y^​)2)

Where

y = Actual Value,
ŷ = Predicted Value

Why Square?

Because,Positive and Negative errors become positive.

Example :    
Actual

[10,20,30]

Prediction

[12,18,35]

Error

2
-2
5

Square

4
4
25

Average

(4+4+25)/3

Loss = 11

In [ ]:
from sklearn.metrics import mean_squared_error

actual = [10,20,30]

predicted = [12,18,35]

loss = mean_squared_error(actual,predicted)

print(loss)

11.0


#b. Binary Cross Entropy

Used For Binary Classification

Output Only ->0 or 1

Examples

Spam/Not Spam

Pass/Fail

Cancer/No Cancer

Formula :
Loss=−[ylog(p)+(1−y)log(1−p)]

Where

y = Actual

p = Prediction

- Intuition

Suppose

Actual

1

Prediction

0.98

Loss

Very Small

Good Prediction

Suppose

Prediction

0.10

Loss

Very Large

Bad Prediction

In [ ]:
from sklearn.metrics import log_loss

actual = [1,0,1]

prediction = [0.9,0.2,0.8]

print(log_loss(actual,prediction))

0.18388253942874858


# c.Categorical Cross Entropy

Used For Multi-Class Classification

- Examples

Animal Classification

Dog

Cat

Horse

Bird

Only one class is correct.

- Example

Actual

Dog

Prediction

Dog = 0.80

Cat = 0.10

Horse = 0.05

Bird = 0.05

Loss

Small

Good Prediction


Dog = 0.10

Cat = 0.60

Horse = 0.20

Bird = 0.10

Loss ->Wrong Prediction

Large

In [ ]:
from tensorflow.keras.losses import CategoricalCrossentropy

#3. Backward Propagation
Definition

Backward Propagation is the learning process of a neural network. It calculates how much each weight and bias contributed to the error, then computes gradients so the model knows how to adjust them.

The information flows from the output layer back toward the input layer, which is why it is called backward propagation.

The objective is to reduce the loss by updating the weights in the correct direction.

Real-Life Example

Imagine a student writes an exam and scores 40 out of 100.

The teacher reviews the paper and identifies the mistakes:

Chapter 1 mistakes: 5 marks lost
Chapter 2 mistakes: 20 marks lost
Chapter 3 mistakes: 35 marks lost

The student now knows which topics caused the most errors and focuses on improving those topics.

Similarly, a neural network identifies which weights contributed most to the prediction error and adjusts those weights.

##Flow of Backward Propagation
Prediction->
Calculate Loss->
Compute Gradients->
Update Weights & Biases->
Lower Loss

###Why is Backward Propagation Needed?

Forward propagation only generates predictions.

Backward propagation answers these questions:

- How wrong is the prediction?
- Which weights caused the error?
- How should each weight change to reduce the error?

Without backward propagation, the network would never learn.

###The Role of Gradients

A gradient is the derivative of the loss with respect to a parameter (weight or bias). It tells us:

Direction: Should the weight increase or decrease?
Magnitude: By how much should it change?

Mathematically:
∂L/
∂W

Where:

L = Loss,
W = Weight

Weight Update Formula
Wnew=Wold−η(∂L/∂W)

Where:

η = Learning Rate
∂L/∂W= Gradient

If the gradient is positive, the weight decreases.

If the gradient is negative, the weight increases.

Example

Suppose:

Current Weight = 2.5

Gradient = 0.8

Learning Rate = 0.1

Updated Weight:2.5−(0.1×0.8)=2.42

The weight is adjusted slightly to reduce future errors.


In [ ]:
# Initial values
weight = 2.5
gradient = 0.8
learning_rate = 0.1

# Weight update
new_weight = weight - learning_rate * gradient

print("Old Weight:", weight)
print("Gradient:", gradient)
print("New Weight:", new_weight)

Old Weight: 2.5
Gradient: 0.8
New Weight: 2.42


#4. Gradient Descent
Definition

Gradient Descent is an optimization algorithm used to minimize the loss function by updating the weights and biases in the direction that reduces the error.

Backward propagation computes the gradients, and Gradient Descent uses those gradients to update the parameters.

Real-Life Example

Imagine you are standing on top of a hill and want to reach the lowest point in the valley.

- The slope tells you which direction goes downhill.
- You take a small step.
- Check the slope again.
- Repeat until you reach the bottom.

Similarly:

- The loss function is the height of the hill.
- The gradient is the slope.
- The learning rate is the size of each step.
- Gradient Descent keeps taking steps until the loss is minimized.

Initialize Weights->
Forward Propagation->
Calculate Loss->
Backward Propagation->
Compute Gradients->
Gradient Descent Updates Weights->
Repeat Until Loss is Minimum

Effect of Learning Rate

Too Small: Training is very slow.

Too Large: The model may overshoot the minimum loss and fail to converge.

Optimal: Fast and stable convergence.


In [ ]:
# Initial values
weight = 5
gradient = 3
learning_rate = 0.1

for epoch in range(5):
    weight = weight - learning_rate * gradient
    print(f"Epoch {epoch+1}: Weight = {weight:.2f}")

Epoch 1: Weight = 4.70
Epoch 2: Weight = 4.40
Epoch 3: Weight = 4.10
Epoch 4: Weight = 3.80
Epoch 5: Weight = 3.50


#Complete Deep Learning Training Cycle
Input Data

     │
     ▼
Forward Propagation

     │
     ▼
Prediction

     │
     ▼
Loss Function

     │
     ▼
Backward Propagation

     │
     ▼
Compute Gradients

     │
     ▼
Gradient Descent

     │
     ▼
Update Weights & Biases

     │
     ▼
Repeat for Multiple Epochs

     │
     ▼
Model Learns and Loss Decreases

| Concept              | Purpose                                                                  |
| -------------------- | ------------------------------------------------------------------------ |
| Forward Propagation  | Generates predictions from the input using current weights and biases.   |
| Loss Function        | Measures how far the predictions are from the actual values.             |
| Backward Propagation | Computes gradients to identify how each weight should change.            |
| Gradient Descent     | Updates the weights and biases using the gradients to minimize the loss. |


#Building Neural Networks with TensorFlow/Keras

###What is TensorFlow?

TensorFlow is a tool (framework) that helps computers learn from data and make predictions.

It is developed by Google and is mainly used to build Machine Learning and Deep Learning models.

- Simple Definition

TensorFlow is a framework that helps us create, train, and use AI models.

- Real-Life Example

Imagine you want to teach a child to recognize cats and dogs.

You show many pictures of cats and dogs.
The child learns the differences.
After learning, the child can identify a new picture.

Similarly, TensorFlow helps a computer learn from examples and make predictions.

###What is Keras?

Keras is a library (API) that makes TensorFlow easy to use.

Instead of writing long and complicated code, Keras lets you build a neural network in just a few lines.

- Simple Definition

Keras is a simple interface that makes it easy to build deep learning models using TensorFlow.

- Real-Life Example

Think about driving a car.

 Car Engine → TensorFlow
 Steering Wheel → Keras

The engine (TensorFlow) does all the hard work.
The steering wheel (Keras) helps you control the car easily.

You don't directly control the engine—you use the steering wheel.

Similarly, programmers don't usually write low-level TensorFlow code. They use Keras, and Keras communicates with TensorFlow behind the scenes.

In [ ]:
# ==========================================
# Building a Neural Network using TensorFlow/Keras
# Example: Predict Pass/Fail based on Study Hours
# ==========================================

# Step 1: Import Libraries
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

# ------------------------------------------
# Step 2: Create Dataset
# ------------------------------------------

# Input (Study Hours)
X = np.array([
    [2],
    [4],
    [6],
    [8],
    [10]
])

# Output (0 = Fail, 1 = Pass)
y = np.array([
    0,
    0,
    1,
    1,
    1
])

# ------------------------------------------
# Step 3: Build Neural Network
# ------------------------------------------

model = Sequential([
    Dense(8, activation='relu', input_shape=(1,)),   # Hidden Layer 1
    Dense(4, activation='relu'),                     # Hidden Layer 2
    Dense(1, activation='sigmoid')                   # Output Layer
])

# ------------------------------------------
# Step 4: Compile the Model
# ------------------------------------------

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# ------------------------------------------
# Step 5: Train the Model
# ------------------------------------------

print("Training Started...\n")

history = model.fit(
    X,
    y,
    epochs=100,
    verbose=1
)

print("\nTraining Completed!")

# ------------------------------------------
# Step 6: Evaluate the Model
# ------------------------------------------

loss, accuracy = model.evaluate(X, y, verbose=0)

print("\nModel Evaluation")
print("-----------------------")
print("Loss     :", round(loss, 4))
print("Accuracy :", round(accuracy * 100, 2), "%")

# ------------------------------------------
# Step 7: Make Predictions
# ------------------------------------------

print("\nPredictions")
print("-----------------------")

test_data = np.array([
    [3],
    [5],
    [7],
    [9]
])

predictions = model.predict(test_data)

for hours, pred in zip(test_data, predictions):
    probability = pred[0]

    if probability >= 0.5:
        result = "Pass"
    else:
        result = "Fail"

    print(f"Study Hours: {hours[0]} -> Probability: {probability:.4f} -> Prediction: {result}")

# ------------------------------------------
# Step 8: Model Summary
# ------------------------------------------

print("\nModel Summary")
print("-----------------------")
model.summary()

# ------------------------------------------
# Step 9: Display Weights and Biases
# ------------------------------------------

print("\nModel Weights and Biases")
print("-----------------------")

for i, layer in enumerate(model.layers):
    weights, biases = layer.get_weights()

    print(f"\nLayer {i+1}")
    print("Weights:")
    print(weights)

    print("Biases:")
    print(biases)

# ------------------------------------------
# Step 10: Predict for a New Student
# ------------------------------------------

study_hours = 3

prediction = model.predict(np.array([[study_hours]]))

print("\nNew Student Prediction")
print("-----------------------")
print("Study Hours :", study_hours)
print("Probability :", prediction[0][0])

if prediction[0][0] >= 0.5:
    print("Final Prediction : PASS")
else:
    print("Final Prediction : FAIL")

Training Started...

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.4000 - loss: 1.2964
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 0.4000 - loss: 1.2866
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.4000 - loss: 1.2769
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.4000 - loss: 1.2672
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.4000 - loss: 1.2577
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.4000 - loss: 1.2482
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.4000 - loss: 1.2388
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.4000 - loss: 1.2295
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.4000 - loss: 1.2202
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.4000 - loss: 1.2111
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.4000 - loss: 1.2020
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - a

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 253ms/step
Study Hours: 3 -> Probability: 0.5192 -> Prediction: Pass
Study Hours: 5 -> Probability: 0.5082 -> Prediction: Pass
Study Hours: 7 -> Probability: 0.4973 -> Prediction: Fail
Study Hours: 9 -> Probability: 0.4863 -> Prediction: Fail

Model Summary
-----------------------


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 8)              │            16 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 4)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 173 (696.00 B)

 Trainable params: 57 (228.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 116 (468.00 B)


Model Weights and Biases
-----------------------

Layer 1
Weights:
[[ 0.52014893 -0.09267908 -0.03696626 -0.6637504   0.5493576   0.5818767
  -0.15773183 -0.43151268]]
Biases:
[-0.0505743   0.          0.          0.          0.08199095 -0.06968258
  0.          0.        ]

Layer 2
Weights:
[[ 0.7634219  -0.41798022 -0.47187525  0.5574547 ]
 [ 0.6036075  -0.24966833  0.25253952 -0.14930099]
 [ 0.6274906  -0.27445826  0.3662166   0.5324796 ]
 [ 0.2265206  -0.5487717   0.30943793 -0.38617   ]
 [-0.32591256  0.14862716 -0.6449127  -0.34283534]
 [ 0.32243583  0.2062326  -0.64118844  0.5185756 ]
 [-0.14433843  0.04452598  0.5401383   0.66062874]
 [-0.36270094  0.6895893   0.3766505  -0.10717642]]
Biases:
[ 0.08711513  0.          0.         -0.07811659]

Layer 3
Weights:
[[ 0.30419242]
 [ 0.18342912]
 [-0.80678076]
 [-0.36027452]]
Biases:
[0.081286]


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 275ms/step

New Student Prediction
-----------------------
Study Hours : 1
Probability : 0.5302601
Final Prediction : FAIL
Training Started...

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.6000 - loss: 0.5854
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.6000 - loss: 0.5822
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.6000 - loss: 0.5790
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6000 - loss: 0.5759
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.6000 - loss: 0.5728
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6000 - loss: 0.5699
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.6000 - loss: 0.5670
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6000 - loss: 0.5642
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.6000 - loss: 0.5615
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6000 - lo

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 8)              │            16 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 4)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 173 (696.00 B)

 Trainable params: 57 (228.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 116 (468.00 B)


Model Weights and Biases
-----------------------

Layer 1
Weights:
[[-0.5518352  -0.39212397  0.4470727   0.38993862  0.2930588   0.4940554
  -0.2635345  -0.7678228 ]]
Biases:
[ 0.          0.         -0.08141812 -0.0810012   0.01122769  0.02882017
  0.          0.        ]

Layer 2
Weights:
[[ 0.5825606  -0.5217707   0.42473286 -0.34847066]
 [-0.5922826  -0.4293501  -0.39513782  0.10819536]
 [-0.27255258  0.50306535 -0.17270511  0.10190147]
 [ 0.39999837  0.0930742  -0.09287363 -0.53154445]
 [ 0.54908836 -0.41074193  0.20422882 -0.09936506]
 [-0.2953662   0.18140061 -0.51333594 -0.04938346]
 [ 0.4921927  -0.41894186 -0.43996352 -0.5460333 ]
 [ 0.24293947  0.37013918  0.53439707 -0.28069413]]
Biases:
[-0.08413669 -0.08522707  0.          0.        ]

Layer 3
Weights:
[[ 0.6506442 ]
 [ 0.88750076]
 [-0.63551354]
 [-0.4573058 ]]
Biases:
[-0.08603147]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step

New Student Prediction
-----------------------
Study Hours : 3
Probability : 0.60882103
Final Predi