<a href="https://colab.research.google.com/github/gayathri9381/TNS.ipynb/blob/main/Numpy%26pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
arr=np.zeros(10)
matrix=np.reshape(arr,(2,5))
print(matrix)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
arr=np.arange(2,21,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.size)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
ARR=arr*2
print(ARR)


[[1 2 3]
 [4 5 6]]
6
(2, 3)
int64
2
[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
arr=np.array([1,2,3,4,5])
print(arr.ndim)
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

1
15
3.0
5
1


In [ ]:
import numpy as np
import pandas as pd
s1=pd.Series((1,2,3,4,5,6,7,8))
print(s1)
print(s1.describe())
print(s1.sum())
print(s1.map(lambda x:x*2))
print(s1.apply(lambda x:x*2))
sorts=s1.sort_values()
print(sorts)
dropped=s1.drop(2)
print(dropped)
s2=pd.Series((1,2,3,5,6,np.nan,8))
print(s2.isnull())
print(s2.notnull())
print(s2.fillna(0))
print(s2.dropna())
print(s2.iloc[2])
greater_num=s2[s2>5]
print(greater_num)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64
count    8.00000
mean     4.50000
std      2.44949
min      1.00000
25%      2.75000
50%      4.50000
75%      6.25000
max      8.00000
dtype: float64
36
0     2
1     4
2     6
3     8
4    10
5    12
6    14
7    16
dtype: int64
0     2
1     4
2     6
3     8
4    10
5    12
6    14
7    16
dtype: int64
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64
0    1
1    2
3    4
4    5
5    6
6    7
7    8
dtype: int64
0    False
1    False
2    False
3    False
4    False
5     True
6    False
dtype: bool
0     True
1     True
2     True
3     True
4     True
5    False
6     True
dtype: bool
0    1.0
1    2.0
2    3.0
3    5.0
4    6.0
5    0.0
6    8.0
dtype: float64
0    1.0
1    2.0
2    3.0
3    5.0
4    6.0
6    8.0
dtype: float64
3.0
4    6.0
6    8.0
dtype: float64


In [2]:
# create a dataframe
import pandas as pd

data = {
    "Name":["Alice","Bob","Charlie"],
    "Marks":[85,90,78]
}

df = pd.DataFrame(data)
print(df)

      Name  Marks
0    Alice     85
1      Bob     90
2  Charlie     78


In [3]:
# Operations in dataframes

import pandas as pd
import numpy as np

# Create DataFrame
data = {
    "ID": [101, 102, 103, 104, 105],
    "Name": ["Amit", "Bobby", "Charlie", "Danush", "Emily"],
    "Department": ["HR", "IT", "Finance", "IT", "HR"],
    "Age": [25, 30, 28, 35, 29],
    "Salary": [40000, 60000, 55000, 70000, 45000]
}

df = pd.DataFrame(data)

# Display DataFrame
print("\nOriginal DataFrame:")
print(df)

# Basic Information
print("\nHead:")
print(df.head())

print("\nTail:")
print(df.tail())

print("\nShape:")
print(df.shape)

print("\nColumns:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

print("\nInfo:")
print(df.info())

print("\nDescribe:")
print(df.describe())

# Selecting columns
print("\nName column:")
print(df["Name"])

print("\nMultiple columns:")
print(df[["Name", "Salary"]])

# Filtering
print("\nSalary > 50000:")
print(df[df["Salary"] > 50000])

# loc and iloc
print("\nloc:")
print(df.loc[1:3])

print("\niloc:")
print(df.iloc[0:3, 1:4])

# Adding columns
df["Bonus"] = df["Salary"] * 0.1
print("\nAfter Adding Bonus:")
print(df)

# Updating values
df.loc[df["Name"] == "Bob", "Salary"] = 65000
print("\nUpdated Salary:")
print(df)

# Sorting
print("\nSorted by Salary:")
print(df.sort_values(by="Salary", ascending=False))

# Unique values
print("\nUnique Departments:")
print(df["Department"].unique())

print("\nNumber of Unique Departments:")
print(df["Department"].nunique())

# Value counts
print("\nDepartment Counts:")
print(df["Department"].value_counts())

# Groupby
print("\nAverage Salary Department-wise:")
print(df.groupby("Department")["Salary"].mean())

# Aggregation
print("\nAggregations:")
print(df["Salary"].agg(["min", "max", "mean", "sum"]))

# Missing values
print("\nMissing Values:")
print(df.isnull())

print("\nMissing Values Count:")
print(df.isnull().sum())

# Fill missing values
df.fillna(0, inplace=True)

# Duplicate rows
print("\nDuplicate Rows:")
print(df.duplicated())

df.drop_duplicates(inplace=True)

# Rename columns
df.rename(columns={"Age": "Employee_Age"}, inplace=True)

# Drop column
df.drop(columns=["Bonus"], inplace=True)

# Correlation
print("\nCorrelation:")
print(df.select_dtypes(include=np.number).corr())

# Pivot Table
print("\nPivot Table:")
print(pd.pivot_table(df,
                     values="Salary",
                     index="Department",
                     aggfunc="mean"))

# Statistical functions
print("\nMaximum Salary:", df["Salary"].max())
print("Minimum Salary:", df["Salary"].min())
print("Mean Salary:", df["Salary"].mean())
print("Median Salary:", df["Salary"].median())
print("Standard Deviation:", df["Salary"].std())

# Sampling
print("\nRandom Sample:")
print(df.sample(2))

# Index operations
print("\nIndex:")
print(df.index)

# Reset index
df.reset_index(drop=True, inplace=True)

# Export to CSV
df.to_csv("employee.csv", index=False)

# Read CSV
new_df = pd.read_csv("employee.csv")

print("\nFinal DataFrame:")
print(new_df)


Original DataFrame:
    ID     Name Department  Age  Salary
0  101     Amit         HR   25   40000
1  102    Bobby         IT   30   60000
2  103  Charlie    Finance   28   55000
3  104   Danush         IT   35   70000
4  105    Emily         HR   29   45000

Head:
    ID     Name Department  Age  Salary
0  101     Amit         HR   25   40000
1  102    Bobby         IT   30   60000
2  103  Charlie    Finance   28   55000
3  104   Danush         IT   35   70000
4  105    Emily         HR   29   45000

Tail:
    ID     Name Department  Age  Salary
0  101     Amit         HR   25   40000
1  102    Bobby         IT   30   60000
2  103  Charlie    Finance   28   55000
3  104   Danush         IT   35   70000
4  105    Emily         HR   29   45000

Shape:
(5, 5)

Columns:
Index(['ID', 'Name', 'Department', 'Age', 'Salary'], dtype='object')

Data Types:
ID             int64
Name          object
Department    object
Age            int64
Salary         int64
dtype: object

Info:
<class 'pand